# Generated by Django 5.0.8 on 2024-11-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Назва кофейни')),
                ('description', models.CharField(max_length=300, verbose_name='Опис')),
                ('address', models.CharField(max_length=170, verbose_name='Адресса')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='Координаты на карте')),
                ('opening_time', models.TimeField(verbose_name='Час відкриття')),
                ('closing_time', models.TimeField(verbose_name='Час закриття')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(verbose_name='Номер столика')),
                ('seats', models.PositiveIntegerField(verbose_name='Кількість місць за столиком')),
                ('is_avaible', models.BooleanField(default=True, verbose_name='Доступный')),
                ('coffeehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='coffeehouses.coffeehouse', verbose_name='Кофейня')),
            ],
        ),
    ]
