# Generated by Django 5.0.8 on 2024-12-05 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_avaible',
        ),
        migrations.AddField(
            model_name='table',
            name='booking_duration',
            field=models.TimeField(default="00:00:00", verbose_name='Продовжуваність бронювання'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeehouse',
            name='name',
            field=models.CharField(max_length=155, verbose_name="Назва кав'ярні"),
        ),
    ]
