# Generated by Django 5.0.8 on 2024-12-05 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouses', '0002_remove_table_is_avaible_table_booking_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='booking_duration',
        ),
    ]
