# Generated by Django 5.0.8 on 2025-04-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouses', '0005_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeehouse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffeehouses_images', verbose_name='Зображення'),
        ),
    ]
