# Generated by Django 5.0.8 on 2024-11-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffeehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name="Ім'я кліета")),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('reservation_date', models.DateField(verbose_name='Дата бронювання')),
                ('reservation_time', models.TimeField(verbose_name='Час бронювання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('coffeehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='coffeehouses.coffeehouse', verbose_name='Столик')),
            ],
        ),
    ]
