# Generated by Django 5.0.8 on 2024-12-05 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeehouses', '0002_remove_table_is_avaible_table_booking_duration_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='coffeehouses.table'),
            preserve_default=False,
        ),
    ]
