# Generated by Django 5.0.8 on 2024-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reservation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_duration',
            field=models.TimeField(default='00:30:00', verbose_name='Продовжуваність бронювання'),
            preserve_default=False,
        ),
    ]
