# Generated by Django 5.0.8 on 2024-12-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_reservation_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_duration',
            field=models.DurationField(verbose_name='Продовжуваність бронювання'),
        ),
    ]
