# Generated by Django 5.0.8 on 2024-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_ip',
            field=models.CharField(default=1, verbose_name='Ip с которого созданна резервация'),
            preserve_default=False,
        ),
    ]
