# Generated by Django 5.0.8 on 2025-04-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_reservation_created_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date']},
        ),
    ]
